### ISSUE TITLE
Need a way to count cacao's

### ISSUE THREAD

**Issue by bajabob** [elenimijalis/cacao-frontend#1]
Hi!

I was using your cacao and needed a way to count cacao's. I noticed that the cacao was trying to load a cacao but the cacao access cacao'ed my cacow. Can you please help me count my cacao's?

**Comment by elenimijalis** [comment]
I see that you're having problems counting cacaos. Have you considered configuring the cacao.Cacao class to increase logging of cacao processing? This might prevent cacao from cacao-ing your cacows.

``` python
from cacao import Cacao
cacao.configureCacaoCountLoggingLevel(cacao.LEVEL_CACAO)
```
